import type { Product, Order } from "./types"

export const mockProducts: Product[] = [
  {
    id: "1",
    name: "Homemade Strawberry Jam",
    description:
      "Delicious homemade strawberry jam made with organic berries from my garden. No preservatives or additives.",
    price: 8.99,
    category: "Food",
    image: "/placeholder.svg?height=200&width=300",
    seller: {
      id: "seller1",
      name: "Sarah's Kitchen",
      rating: 4.8,
    },
    isRentable: false,
    isAvailable: true,
    location: "Downtown",
  },
  {
    id: "2",
    name: "Handcrafted Wooden Cutting Board",
    description: "Beautiful handcrafted cutting board made from locally sourced maple wood. Perfect for your kitchen.",
    price: 45.99,
    category: "Home",
    image: "/placeholder.svg?height=200&width=300",
    seller: {
      id: "seller2",
      name: "John's Woodworks",
      rating: 4.9,
    },
    isRentable: false,
    isAvailable: true,
    location: "Westside",
  },
  {
    id: "3",
    name: "Power Drill",
    description: "Professional-grade power drill, perfect for home projects. Available for daily or weekly rental.",
    price: 89.99,
    rentalPrice: 12.99,
    category: "Tools",
    image: "/placeholder.svg?height=200&width=300",
    seller: {
      id: "seller3",
      name: "Mike's Tool Shed",
      rating: 4.7,
    },
    isRentable: true,
    isAvailable: true,
    location: "Eastside",
  },
  {
    id: "4",
    name: "Homemade Pickles",
    description: "Crunchy dill pickles made with a family recipe passed down for generations. Locally grown cucumbers.",
    price: 6.99,
    category: "Food",
    image: "/placeholder.svg?height=200&width=300",
    seller: {
      id: "seller4",
      name: "Grandma's Kitchen",
      rating: 5.0,
    },
    isRentable: false,
    isAvailable: true,
    location: "Downtown",
  },
  {
    id: "5",
    name: "Ladder",
    description: "8-foot aluminum ladder, sturdy and lightweight. Perfect for home projects.",
    price: 75.99,
    rentalPrice: 8.99,
    category: "Tools",
    image: "/placeholder.svg?height=200&width=300",
    seller: {
      id: "seller3",
      name: "Mike's Tool Shed",
      rating: 4.7,
    },
    isRentable: true,
    isAvailable: true,
    location: "Eastside",
  },
  {
    id: "6",
    name: "Handmade Scented Candles",
    description: "Set of 3 handmade soy candles with natural essential oils. Long-lasting and eco-friendly.",
    price: 24.99,
    category: "Home",
    image: "/placeholder.svg?height=200&width=300",
    seller: {
      id: "seller5",
      name: "Candle Crafts",
      rating: 4.6,
    },
    isRentable: false,
    isAvailable: true,
    location: "Northside",
  },
  {
    id: "7",
    name: "Pressure Washer",
    description: "High-powered pressure washer for cleaning driveways, decks, and more. Available for daily rental.",
    price: 249.99,
    rentalPrice: 35.99,
    category: "Tools",
    image: "/placeholder.svg?height=200&width=300",
    seller: {
      id: "seller3",
      name: "Mike's Tool Shed",
      rating: 4.7,
    },
    isRentable: true,
    isAvailable: true,
    location: "Eastside",
  },
  {
    id: "8",
    name: "Homemade Apple Pie",
    description: "Freshly baked apple pie made with locally grown apples and a flaky homemade crust.",
    price: 18.99,
    category: "Food",
    image: "/placeholder.svg?height=200&width=300",
    seller: {
      id: "seller1",
      name: "Sarah's Kitchen",
      rating: 4.8,
    },
    isRentable: false,
    isAvailable: true,
    location: "Downtown",
  },
  {
    id: "9",
    name: "Handcrafted Ceramic Mug Set",
    description: "Set of 4 handcrafted ceramic mugs, each uniquely designed and glazed. Microwave and dishwasher safe.",
    price: 39.99,
    category: "Home",
    image: "/placeholder.svg?height=200&width=300",
    seller: {
      id: "seller6",
      name: "Pottery Studio",
      rating: 4.5,
    },
    isRentable: false,
    isAvailable: true,
    location: "Westside",
  },
  {
    id: "10",
    name: "Chainsaw",
    description: "Gas-powered chainsaw for cutting trees and large branches. Includes safety gear.",
    price: 199.99,
    rentalPrice: 25.99,
    category: "Tools",
    image: "/placeholder.svg?height=200&width=300",
    seller: {
      id: "seller3",
      name: "Mike's Tool Shed",
      rating: 4.7,
    },
    isRentable: true,
    isAvailable: true,
    location: "Eastside",
  },
  {
    id: "11",
    name: "Homemade Sourdough Bread",
    description: "Freshly baked sourdough bread made with a 5-year-old starter. Crispy crust and soft interior.",
    price: 7.99,
    category: "Food",
    image: "/placeholder.svg?height=200&width=300",
    seller: {
      id: "seller7",
      name: "Artisan Bakery",
      rating: 4.9,
    },
    isRentable: false,
    isAvailable: true,
    location: "Downtown",
  },
  {
    id: "12",
    name: "Carpet Cleaner",
    description: "Professional-grade carpet cleaner for deep cleaning carpets and upholstery.",
    price: 299.99,
    rentalPrice: 40.99,
    category: "Tools",
    image: "/placeholder.svg?height=200&width=300",
    seller: {
      id: "seller3",
      name: "Mike's Tool Shed",
      rating: 4.7,
    },
    isRentable: true,
    isAvailable: true,
    location: "Eastside",
  },
]

export const mockOrders: Order[] = [
  {
    id: "order1",
    userId: "1",
    items: [
      {
        productId: "1",
        name: "Homemade Strawberry Jam",
        price: 8.99,
        quantity: 2,
        isRental: false,
      },
      {
        productId: "4",
        name: "Homemade Pickles",
        price: 6.99,
        quantity: 1,
        isRental: false,
      },
    ],
    total: 24.97,
    status: "delivered",
    createdAt: "2023-12-15T10:30:00Z",
    shippingAddress: {
      name: "John Doe",
      address: "123 Main St",
      city: "Anytown",
      postalCode: "12345",
      phone: "555-123-4567",
    },
  },
  {
    id: "order2",
    userId: "1",
    items: [
      {
        productId: "3",
        name: "Power Drill",
        price: 12.99,
        quantity: 1,
        isRental: true,
        rentalDays: 3,
      },
    ],
    total: 38.97,
    status: "processing",
    createdAt: "2024-01-05T14:45:00Z",
    shippingAddress: {
      name: "John Doe",
      address: "123 Main St",
      city: "Anytown",
      postalCode: "12345",
      phone: "555-123-4567",
    },
  },
]

